image: node:latest
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g grunt-cli
          - npm install
          - npm version
          - grunt
